<a href="https://colab.research.google.com/github/Deendayal6265/Python-Deendayal/blob/main/Scikit%20Learn/Scikit_Learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#    --------------------------      **Deendayal Jatav**

In [ ]:
# from sklearn.family import Model

from sklearn.linear_model import LinearRegression


**Suport Vector Machine **

SVM is a supervised machine learning algorithm which can be used for both classification or regression challanges. 


... It tries to define a hyperplane which can split the data in the most optimal way . 



In [ ]:
import pandas as pd 
import numpy as np


In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Iris.csv")


In [ ]:
dataset

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
# break the dataset in x( independent ) or y( dependent )

x = dataset.iloc[:,1:5]
print(x)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]


In [ ]:
# array ban jaega
x = dataset.iloc[:,1:5].values
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
y = dataset.iloc[:,5].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [ ]:
print(type(y_test))

<class 'numpy.ndarray'>


In [ ]:
# decoding the y 
# now y in a string form but we change it into the numerical form 

from sklearn.preprocessing import LabelEncoder

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)


print("y is succesfully encoded ")


y is succesfully encoded 


In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# divide the data into training and testing data . 

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20)


# Logistic Regression 


In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
y_pred = logmodel.predict(x_test)

In [ ]:
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
y_test

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 1, 0, 2, 1, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  7]])

In [ ]:
27/30

0.9

# K NEIGHBORS 

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski',p=2)
classifier_knn.fit(x_train, y_train)


KNeighborsClassifier()

In [ ]:
y_pred = classifier_knn.predict(x_test)

y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  7]])

In [ ]:
# accuracy of the model.
(10+6+11)/30

0.9

# **Naive Bayes ** 


In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred = classifier_nb.predict(x_test)
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  7]])

In [ ]:
(8+8+14)/30

1.0

# ** Support Vector Machine (SVM)  -- Sigmoid **

In [ ]:
from sklearn.svm import SVC
classifier_svm_sigmoid = SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)



SVC(kernel='sigmoid')

In [ ]:
y_pred = classifier_svm_sigmoid.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[ 0,  0, 12],
       [ 0,  0, 11],
       [ 0,  0,  7]])

In [ ]:
(5+2+0)/30     # here model accuracy is very low . 


0.23333333333333334

## **Support Vector Machine (SVM) --- Linear**

In [ ]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear')
classifier_svm_linear.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
y_pred = classifier_svm_linear.predict(x_test)
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  7]])

In [ ]:
(8+8+13)/30

0.9666666666666667

### **bold text** **Support Vector Machine (SVM)----- (rbf)**

In [ ]:
from sklearn.svm import SVC
classifier_svm_rbf = SVC(kernel='rbf')
classifier_svm_rbf.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = classifier_svm_rbf.predict(x_test)
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  7]])

In [ ]:
(8+8+13)/30

0.9666666666666667

# **Support Vector Machine (SVM)-----poly**

In [ ]:
from sklearn.svm import SVC
classifier_svm_poly = SVC(kernel='poly')
classifier_svm_poly.fit(x_train,y_train)

SVC(kernel='poly')

In [ ]:
y_pred = classifier_svm_poly.predict(x_test)
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  0,  7]])

In [ ]:
(8+8+13)/30

0.9666666666666667

# **SVM - Decision tree classifier **

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
y_pred = classifier_dt.predict(x_test)
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 1, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  1,  6]])

In [ ]:
(8+8+14)/30  # very high accuracy .... 

1.0

# **Random Forest Classifier  **

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion = 'entropy')
classifier_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=3)

In [ ]:
y_pred = classifier_rf.predict(x_test)
y_pred

array([2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 2, 1, 0,
       0, 0, 0, 2, 0, 2, 1, 1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[12,  0,  0],
       [ 0, 10,  1],
       [ 0,  1,  6]])

In [ ]:
(8+8+14)/30  # very high Accuracy ... .

1.0